nome = str(input("Digite seu nome completo: ")).strip()
print(f"Seu nome em maiúsculas é {nome.upper()} ")
print(f"Seu nome em minúsculas é {nome.lower()} ")
print(f"Seu nome tem {len(nome)} letras")
print(f"Seu primeiro nome é {nome.split()[0]} e ele tem {len(nome.split()[0])} letras ")
